### ISSUE TITLE
Dockerfile for ansible 2.9 take the latest mitogen version

### ISSUE THREAD

**Issue by lirany1** [willhallonline/docker-ansible#43]
`pip3 install mitogen ansible-lint jmespath && \`

from mitogen site:
```
v0.3.0 (unreleased)
This release separates itself from the v0.2.X releases. Ansible’s API changed too much to support backwards compatibility so from now on, v0.2.X releases will be for Ansible < 2.10 and v0.3.X will be for Ansible 2.10+. See here for details.
```

how can we use a specific version of mitogen with this ansible image?

```
    - name: ansible
      image: willhallonline/ansible:2.9-alpine-3.13
      command: [cat]
      tty: true
      imagePullPolicy: Always
      env:
        - name: ANSIBLE_FORKS
          value: 20
        - name: ANSIBLE_STRATEGY
          value: mitogen_linear
        - name: ANSIBLE_PIPELINING
          value: True
        - name: ANSIBLE_STRATEGY_PLUGINS
          value: /usr/lib/python3.8/site-packages/ansible_mitogen/plugins/strategy
        - name: ANSIBLE_SSH_PIPELINING
          value: True
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: False
        - name: ANSIBLE_GATHERING
          value: smart
        - name: ANSIBLE_CACHE_PLUGIN_CONNECTION
          value: /tmp/facts_cache
        - name: ANSIBLE_CACHE_PLUGIN
          value: jsonfile
        - name: ANSIBLE_CACHE_PLUGIN_TIMEOUT
          value: 7200
        - name: ANSIBLE_SSH_RETRIES
          value: 3
        - name: ANSIBLE_TIMEOUT
          value: 60
```
